### ISSUE TITLE
Add extension point for 'extension_attributes' of paymentData

### ISSUE THREAD

**Issue by tangar76** [globalpayments/ecommerce-magento-2#21]
You have your own model `view/frontend/web/js/action/set-payment-method.js`.
Unfortunately there is no easy way to add values to 'extension_attributes'.
A lot of modules at checkout `extension_attributes` to pass data to server and process it there.

You have workaround for checkout agreements. But it doesn't cover other third-party modules.

**Comment by ahumulescu** [comment]
Hello @tangar76, can you give me an example of a module that uses 'extension_attributes' at checkout? Thank you!

**Comment by tangar76** [comment]
Recently I had to deal with `swissup/module-recaptcha`. Unfortunately this module private.

But it is implemented in the same way as `magento/module-checkout-agreements` module. Two JS mixins to add agreements info to paymentData:
  - _Magento_Checkout/js/action/place-order_
  - _Magento_Checkout/js/action/set-payment-information_

**Comment by ahumulescu** [comment]
Hello @tangar76, thank you for your answer. Those classes will be useful as an example for the implementation.
Still, you said something about some third-party modules that use the property at checkout to pass data.
Do you know any module that does that, because it will be useful for testing the implementation. If not, no problem, I will search for one.

**Comment by tangar76** [comment]
@ahumulescu I had to deal with few checkout modules from Swissuplabs that uses 'extension_attributes'. Unfortunately all of them are private

**Comment by ahumulescu** [comment]
Hello @tangar76, we've added the possibility to add "extension_attributes" to the paymentData object in our latest release (3.3.1)
